### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by apxltd** [Inedo/UniversalPackageExplorer#1]
This should be as easy to install as possible, and have various distro options:

* UPack (on Inedo's UPack), containing just the binaries
* Downloadable as zip (?contentOnly=zip from feed)
* msi (created from visual studio installer project wizard -- just creates shortcut in program files)
* chocolately package (runs msi silently)
* clickonce app (this handles upgrading)

At this time, we won't use Romp, because it's meant to be in user space.

**Comment by apxltd** [comment]
@gdivis FYI

**Comment by BenLubar** [comment]
If we add the `MSBuild.ILMerge.Task` NuGet package, we can make UniversalPackageExplorer.exe standalone like upack.exe is.

**Comment by gdivis** [comment]
ILMerge didn't used to work with WPF applications. Has it been updated to fix that?

**Comment by apxltd** [comment]
And also, these nonsense scanning tools seem to be unhappy with ILMunging, from past experience and what I've read.

⚠️ VIRUS ALERT ⚠️ 

Who knows if it's true anymore.

**Comment by BenLubar** [comment]
https://www.virustotal.com/#/file/1b03d84e479be799395ca058a9bd5a18ba21155b4d5717017bfebe3f73ba3634/detection

Nothing detects it as a virus. For now, at least.

**Comment by apxltd** [comment]
Closing, because it's just a dciussion / placeholder
